### RECUPERAR TODAS LAS PELICULAS
GET http://localhost:1234/movies 

### RECUPERAR PELICULAS POR ID
GET http://localhost:1234/movies/3982031b-849d-4952-ac7f-4ab72255ab0a

### RECUPERAR PELICULAS POR GENERO
GET http://localhost:1234/movies?genre=crime

###CREAR UNA PELICULA CON UN POST 
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1972,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
        "Drama"
    ],
    "rate": 9.2
}

###ACTUALIZAR UNA PELICULA CON PATHc
PATCH http://localhost:1234/movies/3a3035a8-fda6-47ae-98e2-f6058dc8be41
Content-Type: application/json

{
    "year": 2025
}